FROM openjdk:19-alpine
LABEL authors="José Alisson"

ARG URL
ARG USERNAME
ARG PASSWORD
ARG API_MAIN

ENV DATABASE_URL=${URL}
ENV DATABASE_USERNAME=${USERNAME}
ENV DATABASE_PASSWORD=${PASSWORD}
ENV API_MAIN=${API_MAIN}

EXPOSE 8080

WORKDIR /main
COPY target/joliny-pedidos-0.0.1-SNAPSHOT.jar .

CMD ["java", "-jar", "/main/joliny-pedidos-0.0.1-SNAPSHOT.jar"]
